development:
  adapter: postgresql
  encoding: unicode
  database: rails_challenges
  pool: 5
  username: postgres
  password: root
  host: localhost
  timeout: 5000 

test:
  adapter: postgresql
  encoding: unicode
  database: myapp_test
  pool: 5
  username: postgres
  password: root
  host: localhost
  timeout: 5000
